import clsx from "clsx";
import { Rubik } from "next/font/google";
import Head from "next/head";
import { useCallback, useEffect, useRef } from "react";

const font = Rubik({
  subsets: ["latin-ext"],
});

export default function Login() {
  const sayHello = useCallback(async () => {
    const resp = await fetch("/api/hello");
    const respJson = (await resp.json()) as { message: string };
  }, []);

  useEffect(() => {
    sayHello()
      .then((a) => {
        console.log(a);
      })
      .catch((e) => console.error(e));
  }, []);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx("flex h-[100dvh] flex-col", font.className)}>
        <nav className="bg-[#255be3] px-4 py-2">
          <h1 className="text-xl text-white">Citi frame</h1>
        </nav>
        <div className="grid grow place-items-center bg-white px-4 py-2">
          {/* <div className="lds-ring">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
          </div> */}
          Pre login Content
        </div>
        <button
          onClick={() => {
            document.requestStorageAccess().then(
              () => {
                document.cookie = "heyCookie=cookiehter;";
              },
              () => console.log("access denied"),
            );
          }}
        >
          Accept cookies
        </button>
      </main>
    </>
  );
}
