import Head from "next/head";
import { useRouter } from "next/router";
import clsx from "clsx";
import { Rubik } from "next/font/google";

const font = Rubik({
  subsets: ["latin-ext"],
});

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx("flex flex-col", font.className)}>
        <nav className="">
          <h1 className="text-xl">{router.asPath}</h1>
        </nav>
        <div className="grow bg-green-50"></div>
      </main>
    </>
  );
}
