import Head from "next/head";
import clsx from "clsx";
import { Rubik } from "next/font/google";
import { GetServerSideProps } from "next";

const font = Rubik({
  subsets: ["latin-ext"],
});

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  console.log(req.headers.cookie);
  const cookieToken = req.headers.cookie?.split("=")[1];
  if (!cookieToken) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  const parsed = Buffer.from(cookieToken, "base64").toString("utf-8");
  if (parsed !== "This is a secret token") {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  return {
    props: {
      cookie: req.headers.cookie ?? "none",
    },
  };
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx("flex h-[100dvh] flex-col", font.className)}>
        <nav className="bg-[#255be3] px-4 py-2">
          <h1 className="text-xl text-white">Citi frame</h1>
        </nav>
        <div className="grid grow place-items-center bg-green-50 px-4 py-2">
          Post Login Content
        </div>
      </main>
    </>
  );
}
