import { GetServerSideProps } from "next";
import Head from "next/head";

// GetServerSideProps
// export const getServerSideProps: GetServerSideProps = async () => {
//   return {
//     redirect: {
//       destination: "",
//       permanent: false,
//     },
//   };
// };

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
