import Head from "next/head";
import { useEffect } from "react";

export const getServerSideProps = () => {
  return {
    redirect: {
      destination: "/home",
      permanent: false,
    },
  };
};

export default function Home() {
  useEffect(() => {
    document.requestStorageAccess().then(
      () => {
        console.log("storage access granted");
      },
      () => {
        console.log("storage access rejected");
      },
    );
  }, []);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
